export const API_URL = "https://api.smartslydes.com"

export const workarea = {
    "type": "image",
    "version": "3.6.6",
    "originX": "left",
    "originY": "top",
    "left": 205,
    "top": -16,
    "width": 600,
    "height": 400,
    "fill": "rgb(0,0,0)",
    "stroke": null,
    "strokeWidth": 0,
    "strokeDashArray": null,
    "strokeLineCap": "butt",
    "strokeDashOffset": 0,
    "strokeLineJoin": "miter",
    "strokeMiterLimit": 4,
    "scaleX": 1,
    "scaleY": 1,
    "angle": 0,
    "flipX": false,
    "flipY": false,
    "opacity": 1,
    "shadow": null,
    "visible": true,
    "clipTo": null,
    "backgroundColor": "#fff",
    "fillRule": "nonzero",
    "paintFirst": "fill",
    "globalCompositeOperation": "source-over",
    "transformMatrix": null,
    "skewX": 0,
    "skewY": 0,
    "crossOrigin": "",
    "cropX": 0,
    "cropY": 0,
    "id": "workarea",
    "name": "",
    "file": null,
    "src": "",
    "link": {},
    "tooltip": {
        "enabled": false
    },
    "layout": "fixed",
    "workareaWidth": 600,
    "workareaHeight": 400,
    "card-type": null,
    "correct-answer": null,
    "drag-destination": null,
    "correct-animation": null,
    "wrong-animation": null,
    "filters": []
}
